/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\xingkong\\lzx-vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7b03c9bc",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b03c9bc").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-290eff02",
    path: "/exist/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-290eff02").then(next)
    },
  },
  {
    path: "/exist/index.html",
    redirect: "/exist/"
  },
  {
    name: "v-3f4f29cc",
    path: "/exist/a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f4f29cc").then(next)
    },
  },
  {
    name: "v-734327f6",
    path: "/readList/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-734327f6").then(next)
    },
  },
  {
    path: "/readList/index.html",
    redirect: "/readList/"
  },
  {
    name: "v-12d61874",
    path: "/readList/a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12d61874").then(next)
    },
  },
  {
    name: "v-140de76a",
    path: "/skill/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-140de76a").then(next)
    },
  },
  {
    path: "/skill/index.html",
    redirect: "/skill/"
  },
  {
    name: "v-45acae0c",
    path: "/skill/a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45acae0c").then(next)
    },
  },
  {
    name: "v-6be08ef7",
    path: "/website/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6be08ef7").then(next)
    },
  },
  {
    path: "/website/index.html",
    redirect: "/website/"
  },
  {
    name: "v-a7fc0a68",
    path: "/website/a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7fc0a68").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]