/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "d:\\xingkong\\lzx-vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-b38791fc",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b38791fc").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-b2e86742",
    path: "/exist/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2e86742").then(next)
    },
  },
  {
    path: "/exist/index.html",
    redirect: "/exist/"
  },
  {
    name: "v-7868ecb3",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7868ecb3").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-1bd91128",
    path: "/exist/homeEducation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1bd91128").then(next)
    },
  },
  {
    name: "v-01812fdc",
    path: "/exist/poorBusy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01812fdc").then(next)
    },
  },
  {
    name: "v-5a559d5a",
    path: "/exist/remoteWork.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a559d5a").then(next)
    },
  },
  {
    name: "v-879ce628",
    path: "/exist/tecProgress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-879ce628").then(next)
    },
  },
  {
    name: "v-0c0fa9dc",
    path: "/exist/timeAndMoney.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c0fa9dc").then(next)
    },
  },
  {
    name: "v-91ee8768",
    path: "/exist/useLess.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-91ee8768").then(next)
    },
  },
  {
    name: "v-64014fe5",
    path: "/readList/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64014fe5").then(next)
    },
  },
  {
    path: "/readList/index.html",
    redirect: "/readList/"
  },
  {
    name: "v-0d4e8be6",
    path: "/readList/a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d4e8be6").then(next)
    },
  },
  {
    name: "v-9de74faa",
    path: "/skill/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9de74faa").then(next)
    },
  },
  {
    path: "/skill/index.html",
    redirect: "/skill/"
  },
  {
    name: "v-25fa43a8",
    path: "/skill/a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25fa43a8").then(next)
    },
  },
  {
    name: "v-daaa2a52",
    path: "/website/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-daaa2a52").then(next)
    },
  },
  {
    path: "/website/index.html",
    redirect: "/website/"
  },
  {
    name: "v-5e831aec",
    path: "/website/a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e831aec").then(next)
    },
  },
  {
    name: "v-58ace39c",
    path: "/website/markDown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58ace39c").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]