/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "LZX's Blog by VuePress",
  "description": "lzx a project",
  "base": "/lzx-vuepress/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/lzx-vuepress/logo.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "Hello VuePress",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7b03c9bc",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "Build Setup",
          "slug": "build-setup"
        }
      ]
    },
    {
      "title": "Hello VuePress",
      "frontmatter": {},
      "regularPath": "/bar/",
      "relativePath": "bar/README.md",
      "key": "v-62e832f2",
      "path": "/bar/",
      "headers": [
        {
          "level": 2,
          "title": "Build Setup",
          "slug": "build-setup"
        }
      ]
    },
    {
      "title": "four",
      "frontmatter": {},
      "regularPath": "/bar/four.html",
      "relativePath": "bar/four.md",
      "key": "v-2f1d48d8",
      "path": "/bar/four.html"
    },
    {
      "title": "three",
      "frontmatter": {},
      "regularPath": "/bar/three.html",
      "relativePath": "bar/three.md",
      "key": "v-1fb5af2c",
      "path": "/bar/three.html"
    },
    {
      "title": "one",
      "frontmatter": {},
      "regularPath": "/foo/one.html",
      "relativePath": "foo/one.md",
      "key": "v-fa9274e8",
      "path": "/foo/one.html"
    },
    {
      "title": "two",
      "frontmatter": {},
      "regularPath": "/foo/two.html",
      "relativePath": "foo/two.md",
      "key": "v-e9468d68",
      "path": "/foo/two.html"
    }
  ],
  "themeConfig": {
    "search": true,
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "博文",
        "items": [
          {
            "text": "bar",
            "link": "/bar/"
          },
          {
            "text": "foo",
            "link": "/foo/"
          }
        ]
      },
      {
        "text": "关于",
        "link": "/about/"
      },
      {
        "text": "Github",
        "link": "https://www.github.com/codeteenager"
      }
    ],
    "sidebar": [
      {
        "title": "bar",
        "collapsable": true,
        "children": [
          [
            "/bar/three",
            "three"
          ],
          [
            "/bar/four",
            "four"
          ]
        ]
      },
      {
        "title": "foo",
        "collapsable": true,
        "children": [
          [
            "/foo/one",
            "one"
          ],
          [
            "/foo/two",
            "two"
          ]
        ]
      }
    ],
    "sidebarDepth": 1,
    "lastUpdated": "Last Updated"
  }
}