/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "LZX's Blog by VuePress",
  "description": "lzx a project,每天进步一点点。",
  "base": "/lzx-vuepress/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/lzx-vuepress/logo.jpg"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/exist/",
      "relativePath": "exist/README.md",
      "key": "v-290eff02",
      "path": "/exist/",
      "lastUpdated": "12/14/2021, 10:30:13 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-8554be5a",
      "path": "/about/",
      "lastUpdated": "12/14/2021, 5:00:50 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/exist/homeEducation.html",
      "relativePath": "exist/homeEducation.md",
      "key": "v-4f78b168",
      "path": "/exist/homeEducation.html",
      "lastUpdated": "12/14/2021, 10:30:13 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/exist/poorBusy.html",
      "relativePath": "exist/poorBusy.md",
      "key": "v-f1e0201c",
      "path": "/exist/poorBusy.html",
      "lastUpdated": "12/14/2021, 10:30:13 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/exist/remoteWork.html",
      "relativePath": "exist/remoteWork.md",
      "key": "v-1641958c",
      "path": "/exist/remoteWork.html",
      "lastUpdated": "12/14/2021, 10:30:13 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/exist/tecProgress.html",
      "relativePath": "exist/tecProgress.md",
      "key": "v-4a96a668",
      "path": "/exist/tecProgress.html",
      "lastUpdated": "12/14/2021, 10:30:13 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/exist/useLess.html",
      "relativePath": "exist/useLess.md",
      "key": "v-01cc87a8",
      "path": "/exist/useLess.html",
      "lastUpdated": "12/14/2021, 10:30:13 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/exist/timeAndMoney.html",
      "relativePath": "exist/timeAndMoney.md",
      "key": "v-d36b5c88",
      "path": "/exist/timeAndMoney.html",
      "lastUpdated": "12/14/2021, 10:30:13 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/readList/",
      "relativePath": "readList/README.md",
      "key": "v-734327f6",
      "path": "/readList/",
      "lastUpdated": "12/14/2021, 10:30:13 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/readList/a.html",
      "relativePath": "readList/a.md",
      "key": "v-12d61874",
      "path": "/readList/a.html",
      "lastUpdated": "12/13/2021, 9:56:06 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/skill/",
      "relativePath": "skill/README.md",
      "key": "v-140de76a",
      "path": "/skill/",
      "lastUpdated": "12/14/2021, 10:30:13 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/skill/a.html",
      "relativePath": "skill/a.md",
      "key": "v-45acae0c",
      "path": "/skill/a.html",
      "lastUpdated": "12/13/2021, 9:56:06 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/website/",
      "relativePath": "website/README.md",
      "key": "v-6be08ef7",
      "path": "/website/",
      "lastUpdated": "12/14/2021, 10:30:13 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/website/a.html",
      "relativePath": "website/a.md",
      "key": "v-a7fc0a68",
      "path": "/website/a.html",
      "lastUpdated": "12/13/2021, 9:56:06 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/website/markDown.html",
      "relativePath": "website/markDown.md",
      "key": "v-6e332612",
      "path": "/website/markDown.html",
      "headers": [
        {
          "level": 2,
          "title": "这是二级标题，二级标题底下有横线",
          "slug": "这是二级标题-二级标题底下有横线"
        },
        {
          "level": 3,
          "title": "这是三级标题",
          "slug": "这是三级标题"
        },
        {
          "level": 2,
          "title": "使用3个或者多个“*”的分割线",
          "slug": "使用3个或者多个-的分割线"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7b03c9bc",
      "path": "/",
      "lastUpdated": "12/13/2021, 10:54:14 AM"
    }
  ],
  "themeConfig": {
    "search": true,
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "博文",
        "items": [
          {
            "text": "CSDN",
            "link": "https://blog.csdn.net/qq_35876316?type=blog"
          }
        ]
      },
      {
        "text": "关于",
        "link": "/about/"
      },
      {
        "text": "Github",
        "link": "https://github.com/fdliu/lzx-vuepress"
      }
    ],
    "sidebar": [
      {
        "title": "技术篇",
        "collapsable": true,
        "children": [
          [
            "/skill/a",
            "帮助"
          ]
        ]
      },
      {
        "title": "生活篇",
        "collapsable": true,
        "children": [
          [
            "/exist/poorBusy",
            "穷忙的人生"
          ],
          [
            "/exist/useLess",
            "那些无用的人"
          ],
          [
            "/exist/tecProgress",
            "技术的进步迫使暴力犯罪越来越少"
          ],
          [
            "/exist/homeEducation",
            "长大后自卑的孩子，大多出自这几种家庭，别不当回事"
          ],
          [
            "/exist/timeAndMoney",
            "能用钱解决的问题，不要花宝贵的时间"
          ],
          [
            "/exist/remoteWork",
            "办公室主导的工作场所将在十年内结束"
          ]
        ]
      },
      {
        "title": "读书清单",
        "collapsable": true,
        "children": [
          [
            "/readList/a",
            "a"
          ]
        ]
      },
      {
        "title": "网站",
        "collapsable": true,
        "children": [
          [
            "/website/a",
            "a"
          ],
          [
            "/website/markDown",
            "markDown"
          ]
        ]
      }
    ],
    "sidebarDepth": 1,
    "lastUpdated": "Last Updated"
  }
}